#******* Roddick et al. PON config *******
model: pon

tfm_channels: 64
ymin: -2
ymax: 4
focal_length: 630.
topdown:
  channels: 128
  layers: [4, 4]
  strides: [1, 2]
  blocktype: bottleneck

# Whether to use Bayesian classifier
bayesian: False

find_unused_params: False

#******* Roddick et al. PON config *******
