#******* Roddick et al. PON config *******

img_size: [256, 512]
map_extents: [-25., 1., 25., 50.]
map_resolution: 0.25

tfm_channels: 64
ymin: -2
ymax: 4
focal_length: 630.
topdown:
  channels: 128
  layers: [4, 4]
  strides: [1, 2]
  blocktype: bottleneck


# Learning rate
learning_rate: 0.1
# Weight decay
weight_decay: 0.0001

# optimizer
optimizer: adam
learning_rate: 0.1

# Scheduler
lr_scheduler: multistep
# Decay learning rate by a factor 10 after the following number of epochs
lr_milestones: [150, 185]
lr_gamma: 0.97

# Binary cross entropy loss weight
xent_weight: 1.0

# Max entropy uncertainty loss weight
uncert_weight: 0.001


#******* Roddick et al. PON config *******
