#******* Lu et al. VED config *******

name: rgved
rgbd: True

num_class: 5

ved:
  # Dimensions of bottleneck (depends on the size of input images)
  bottleneck_dim: 8 

    # ouput_after_vgg must be equal to bottleneck_dim * 128     

# KL-Divergence loss weight
kld_weight: 0.1

find_unused_params: True

#******* Lu et al. VED config *******

# Binary cross entropy loss weight
xent_weight: 1.0

  # Max entropy uncertainty loss weight
uncert_weight: 0.001

# Top-left and bottom right coordinates of map region, in meters
map_extents: [-25., 1., 25., 50.]

# Spacing between adjacent grid cells in the map, in meters
map_resolution: 0.25


