#******************  Experiment options ******************

# Random seed
seed: 1596
resume: False

# Config Files
experiment: none
pc: none
model: none
optimizer: none
dataset: none

# Directory to save experiment to
logdir: none
log_interval: 50

#***********************************************************************
