#******************  Directory options ******************

dataset_root: /home/aircv1/Data/Luis/aisyslab/Daniel/Datasets/
datadir: Front2BEV-RGBD/
# Directory to save experiment to
logdir: /home/aircv1/Data/Luis/aisyslab/Daniel/results/deeplab/

# GPU Options
distributed: True
num_gpus: 4

#******************  Directory options ******************
