
#******************  Directory options ******************

dataset_root: /media/aisyslab/CHINA/Front2BEV-RGBD/

# Directory to save experiment to
logdir: /media/aisyslab/CHINA/results/

# GPU Options
distributed: False
num_gpus: 1

#******************  Directory options ******************
