#******************  Directory options ******************

dataset_root: /media/aisyslab/dan/datasets/
datadir: Front2BEV-RGBD/

# Directory to save experiment to
logdir: /media/aisyslab/dan/results/f2b-rgbd/

# GPU Options
distributed: False
num_gpus: 1

#******************  Directory options ******************
