#******************  Directory options ******************

dataset_root: /home/danielmtz/Data/datasets/
# Directory to save experiment to
logdir: /home/danielmtz/Data/results/f2b-rgbd/

# GPU Options
distributed: True 
num_gpus: 1

#******************  Directory options ******************
