#******************  Directory options ******************

dataset_root: /media/danielmtz/data/datasets/Dan-2023-Front2BEV/

# Directory to save experiment to
logdir: /media/danielmtz/data/results

# GPU Options
distributed: False
num_gpus: 1

#******************  Directory options ******************
