#******************  Directory options ******************

dataset_root: /media/dan/data/datasets/Dan-2024-F2B-Autominy/

# Directory to save experiment to
logdir: /media/dan/data/results

# GPU Options
distributed: False
num_gpus: 1

#******************  Directory options ******************
