#******************  Directory options ******************

# Directory to save experiment to
logdir: /home/dan/Data/results/deeplab/

# GPU Options
distributed: False
num_gpus: 1

#******************  Directory options ******************
