#******************  Dataset options ******************
csv_path: datasets/Dan-2024-Front2BEV-ClassicAug

  #{0: 48981349, 1: 49777705, 2: 30185973, 3: 345667, 4: 69306, 'N': 129360000}

# Prior probability of a positive prediction, used to initialise classifier
prior:
  - 0.37864   # non_drivable_area
  - 0.38479   # drivable_area
  - 0.23334   # walkway
  - 0.00267   # car
  - 0.00056   # pedestrian

class_names: ['non-drivable', 'drivable', 'walkway', 'vehicle', 'pedestrian', 'roadlines']
#******************  Dataset options ******************
